using l2web.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace l2web.helpers
{
    public static class HelperIds
    {
        public static List<Ocupation> classes = new List<Ocupation>
        {
            new Ocupation(0,"Human Fighter"),
            new Ocupation(1,"Human Warrior"),
            new Ocupation(2,"Gladiator"),
            new Ocupation(3,"Warlord"),
            new Ocupation(4,"Human Knight"),
            new Ocupation(5,"Paladin"),
            new Ocupation(6,"Dark Avenger"),
            new Ocupation(7,"Rogue"),
            new Ocupation(8,"Treasure Hunter"),
            new Ocupation(9,"Hawkeye"),
            new Ocupation(10,"Human Mage"),
            new Ocupation(11,"Human Wizard"),
            new Ocupation(12,"Sorcerer"),
            new Ocupation(13,"Necromancer"),
            new Ocupation(14,"Warlock"),
            new Ocupation(15,"Cleric"),
            new Ocupation(16,"Bishop"),
            new Ocupation(17,"Prophet"),
            new Ocupation(18,"Elven Fighter"),
            new Ocupation(19,"Elven Knight"),
            new Ocupation(20,"Temple Knight"),
            new Ocupation(21,"Swordsinger"),
            new Ocupation(22,"Elven Scout"),
            new Ocupation(23,"Plainswalker"),
            new Ocupation(24,"Silver Ranger"),
            new Ocupation(25,"Elven Mage"),
            new Ocupation(26,"Elven Wizard"),
            new Ocupation(27,"Spellsinger"),
            new Ocupation(28,"Elemental Summoner"),
            new Ocupation(29,"Elven Oracle"),
            new Ocupation(30,"Elven Elder"),
            new Ocupation(31,"Dark Elven Fighter"),
            new Ocupation(32,"Pallus Knight"),
            new Ocupation(33,"Shillien Knight"),
            new Ocupation(34,"Bladedancer"),
            new Ocupation(35,"Assasin"),
            new Ocupation(36,"Abyss Walker"),
            new Ocupation(37,"Phantom Ranger"),
            new Ocupation(38,"Dark Elven Mage"),
            new Ocupation(39,"Dark Wizard"),
            new Ocupation(40,"Spellhowler"),
            new Ocupation(41,"Phantom Summoner"),
            new Ocupation(42,"Shillien Oracle"),
            new Ocupation(43,"Shillien Elder"),
            new Ocupation(44,"Orc Fighter"),
            new Ocupation(45,"Orc Raider"),
            new Ocupation(46,"Destroyer"),
            new Ocupation(47,"Monk"),
            new Ocupation(48,"Tyrant"),
            new Ocupation(49,"Orc Mage"),
            new Ocupation(50,"Orc Shaman"),
            new Ocupation(51,"Overlord"),
            new Ocupation(52,"Warcryer"),
            new Ocupation(53,"Dwarven Fighter"),
            new Ocupation(54,"Scavenger"),
            new Ocupation(55,"Bounty Hunter"),
            new Ocupation(56,"Artisan"),
            new Ocupation(57,"Warsmith"),
            new Ocupation(88,"Duelist"),
            new Ocupation(89,"Dread Nought"),
            new Ocupation(90,"Phoenix Knight"),
            new Ocupation(91,"Hell Knight"),
            new Ocupation(92,"Sagittarius"),
            new Ocupation(93,"Adventurer"),
            new Ocupation(94,"Archmage"),
            new Ocupation(95,"Soul Traker"),
            new Ocupation(96,"Arcane Lord"),
            new Ocupation(97,"Cardinal"),
            new Ocupation(98,"Hierophant"),
            new Ocupation(99,"Evas Templar"),
            new Ocupation(100,"Sword Muse"),
            new Ocupation(101,"Wind Rider"),
            new Ocupation(102,"Moonlight Sentinel"),
            new Ocupation(103,"Mystic Muse"),
            new Ocupation(104,"Elemental Master"),
            new Ocupation(105,"Evas Saint"),
            new Ocupation(106,"Shillien Templar"),
            new Ocupation(107,"Spectral Dancer"),
            new Ocupation(108,"Ghost Hunter"),
            new Ocupation(109,"Ghost Sentinel"),
            new Ocupation(110,"Storm Screamers"),
            new Ocupation(111,"Spectral Master"),
            new Ocupation(112,"Shillien Saint"),
            new Ocupation(113,"Titan"),
            new Ocupation(114,"Grand Khauatari"),
            new Ocupation(115,"Dominator"),
            new Ocupation(116,"Doomcryer"),
            new Ocupation(117,"Fortune Seeker"),
            new Ocupation(118,"Maestro"),
            new Ocupation(119,"World Trap"),
            new Ocupation(120,"Player Trap"),
            new Ocupation(121,"Double Ghost"),
            new Ocupation(122,"Siege Attacker"),
            new Ocupation(123,"Male Kamael Soldier"),
            new Ocupation(124,"Female Kamael Soldier"),
            new Ocupation(125,"Trooper"),
            new Ocupation(126,"Warder"),
            new Ocupation(127,"Berserker"),
            new Ocupation(128,"Male Soul Breaker"),
            new Ocupation(129,"Female Soul Breaker"),
            new Ocupation(130,"Arbalester"),
            new Ocupation(131,"Doombringer"),
            new Ocupation(132,"Male Soul Hound"),
            new Ocupation(133,"Female Soul Hound"),
            new Ocupation(134,"Trickster"),
            new Ocupation(135,"Inspector"),
            new Ocupation(136,"Judicator"),

        };

        public static List<Race> races = new List<Race>
        {
            new Race(0,"Human"),
            new Race(1,"Elf"),
            new Race(2,"Dark Elf"),
            new Race(3,"Orc"),
            new Race(4,"Dwarf"),
            new Race(5,"Kamael")
        };

        public static List<EpicJewel> epicIds = new List<EpicJewel>
        {
            new EpicJewel(6657,"Valakas's Necklace"),
            new EpicJewel(6658,"Ring of Baium"),
            new EpicJewel(6659,"Zaken's Earring"),
            new EpicJewel(6660,"Ring of Queen Ant"),
            new EpicJewel(8191,"Frintezza's Necklace"),
            new EpicJewel(90992,"Antharas' Earring")
        };
    }
}
